/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.vanier.main;

import javafx.application.Application;
import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

public class App extends Application {

    public static DoubleProperty STAGE_WIDTH = new SimpleDoubleProperty();
    public static DoubleProperty STAGE_HEIGHT = new SimpleDoubleProperty();
    public static Scene scene ;

    @Override
    public void start(Stage primaryStage) throws Exception {
        
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/Map.fxml"));
        loader.setController(new FXMLController());
        Pane root = loader.load();

        scene = new Scene(root);
   
        //STAGE_WIDTH.bind(primaryStage.widthProperty());
        //STAGE_HEIGHT.bind(primaryStage.heightProperty());
        
        primaryStage.setScene(scene);
        primaryStage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }

}
